CREATE OR REPLACE TYPE T_AREA AS OBJECT (
    ID_AREA NUMBER(10,0),
	TIPO VARCHAR2(100),  
	NOMBRE VARCHAR2(50), 
	PADRES VARCHAR2(4000),
    PROPIEDADES VARCHAR2(4000)
);
/
--DROP TYPE TT_AREA;
CREATE OR REPLACE TYPE TT_AREA IS TABLE OF  T_AREA;
/