CREATE OR REPLACE SYNONYM GISUM_AREA 						FOR "GISUM"."AREA";
CREATE OR REPLACE SYNONYM GISUM_GIS_GRP_TIPO_AREA   		FOR "GISUM"."GI$_GRP_TIPO_AREA";
--CREATE OR REPLACE SYNONYM PKG_API_ADDRESS                   FOR GISUM.PKG_API_ADDRESS;
CREATE OR REPLACE SYNONYM API_ADDRESS_SEGMENT               FOR GISUM.API_ADDRESS_SEGMENT;
CREATE OR REPLACE SYNONYM API_ADDRESS_AREA                  FOR GISUM.API_ADDRESS_AREA;
CREATE OR REPLACE SYNONYM AREA_PROP FOR GISUM.AREA_PROP;
CREATE OR REPLACE SYNONYM AREA_PROP_DEF FOR GISUM.AREA_PROP_DEF;
/
