 
  CREATE TABLE "AREA" 
   (	
    "ID_AREA" NUMBER(10,0),
	"TIPO" VARCHAR2(100), 
	"NOMBRE" VARCHAR2(50), 
	"PADRES" VARCHAR2(4000),
    "PROPIEDADES" VARCHAR2(4000),
	"FECHAMIGRAINI" TIMESTAMP (6), 
	"FECHAMIGRAULT" TIMESTAMP (6), 
	"FECHAMIGRAFIN" TIMESTAMP (6),
    "ID_LOTE_IMPORTACION" NUMBER(20,0),
    "IDENTIFICACION" VARCHAR2(4000)
   ) ;
 
  
  